sudo: false
language: android
jdk: oraclejdk7

android:
    components:
        - build-tools-21.1.2
        - android-22
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository

before_install: chmod +x gradlew

script: ./.util/build.sh

